package:
    name: flopy
    version: "3.1.1"

source:
    git_url: https://github.com/modflowpy/flopy.git
    git_tag: 3.1.1

build:
    number: 1

requirements:
    build:
        - python
        - setuptools
        - numpy 1.9 (or higher)
        - matplotlib 1.4 (or higher)
    run:
        - python
        - numpy 1.9 (or higher)
        - matplotlib 1.4 (or higher)
        - Pyshp 1.2 (or higher) for flopy.plot submodule

about:
    home: https://github.com/modflowpy/flopy/
    license: New BSD
    summary: 'FloPy is a Python package to create, run, and post-process MODFLOW-based models.'
